- name: Install Docker
  hosts: all
  remote_user: pi
  become: true
  tasks:
    - name: Install repository key
      apt_key:
        id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
    - name: Install apt repository
      apt_repository:
        repo: "deb [arch=armhf] https://download.docker.com/linux/debian stretch stable"
        state: present
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install docker-ce
      apt:
        name: docker-ce
    - name: Install docker-ce-cli
      apt:
        name: docker-ce-cli
    - name: Install containerd
      apt:
        name: containerd.io
    - name: Install python-pip
      apt:
        name: python-pip
    - name: Install python-setuptools
      apt:
        name: python-setuptools
    - name: Install virtualenv
      apt:
        name: virtualenv
    - name: Install docker-py
      pip:
        name: docker-py
    - name: Add pi to docker group
      user:
        name: pi
        state: present
        groups: docker
        append: yes

- name: Copy configs
  hosts: all
  remote_user: pi
  tasks:
    - name: Copy project files
      copy:
        src: ../
        dest: ./

- name: Setup Motion
  hosts: nannycam
  remote_user: pi
  tasks:
    - name: Build motion image
      docker_image:
        name: nannycam
        tag: motion
        force: yes
        dockerfile: NannyCam.Motion.Dockerfile
        path: ./docker
    - name: Build nginx image
      docker_image:
        name: nannycam
        tag: nginx
        force: yes
        dockerfile: NannyCam.Nginx.Dockerfile
        path: ./docker
    - name: Create state directory
      file:
        path: /state
        state: directory
    - name: Start motion image
      docker_container:
        name: nannycam-motion
        image: nannycam:motion
        privileged: yes
        restart_policy: always
        ports:
          - "8081:8081"
        volumes:
          - "./config/nannycam-motion:/config:ro"
        devices:
          - "/dev/vchiq"
    - name: Start nginx
      docker_container:
        name: nannycam-nginx
        image: nannycam:nginx
        restart_policy: always
        ports:
          - "8080:80"
        volumes:
          - "/state:/usr/share/nginx/html:ro"
